<?php

/*
 * Auto-generated by libasynql-def
 * Created from init.sql, transaction.sql, account.sql, init.sql
 */

declare(strict_types=1);

namespace SOFe\Capital\Database;

final class Queries{
	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:8
	 *
	 * <h3>Variables</h3>
	 * - <code>:value</code> int, required in account.sql
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_CREATE = "capital.account.create";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:12
	 *
	 * <h3>Variables</h3>
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_FETCH = "capital.account.fetch";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:16
	 *
	 * <h3>Variables</h3>
	 * - <code>:ids</code> string non-empty list, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_FETCH_LIST = "capital.account.fetch_list";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:23
	 *
	 * <h3>Variables</h3>
	 * - <code>:value</code> string, required in account.sql
	 * - <code>:name</code> string, required in account.sql
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_LABEL_ADD = "capital.account.label.add";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:34
	 *
	 * <h3>Variables</h3>
	 * - <code>:name</code> string, required in account.sql
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_LABEL_FETCH = "capital.account.label.fetch";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:38
	 *
	 * <h3>Variables</h3>
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_LABEL_FETCH_ALL = "capital.account.label.fetch_all";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:42
	 *
	 * <h3>Variables</h3>
	 * - <code>:ids</code> string non-empty list, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_LABEL_FETCH_ALL_MULTI = "capital.account.label.fetch_all_multi";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/account.sql:29
	 *
	 * <h3>Variables</h3>
	 * - <code>:value</code> string, required in account.sql
	 * - <code>:name</code> string, required in account.sql
	 * - <code>:id</code> string, required in account.sql
	 */
	public const CAPITAL_ACCOUNT_LABEL_UPDATE = "capital.account.label.update";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/init.sql:12
	 * - resources/sqlite/init.sql:12
	 */
	public const CAPITAL_INIT_ACCOUNT = "capital.init.account";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/init.sql:23
	 * - resources/sqlite/init.sql:24
	 */
	public const CAPITAL_INIT_ACCOUNT_LABEL = "capital.init.account_label";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/init.sql:36
	 * - resources/sqlite/init.sql:38
	 */
	public const CAPITAL_INIT_TRANSACTION = "capital.init.transaction";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/init.sql:84
	 */
	public const CAPITAL_INIT_TRANSACTION_CREATE_PROC = "capital.init.transaction_create_proc";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/init.sql:47
	 * - resources/sqlite/init.sql:50
	 */
	public const CAPITAL_INIT_TRANSACTION_LABEL = "capital.init.transaction_label";

	/**
	 * <h4>Declared in:</h4>
	 * - resources/mysql/transaction.sql:14
	 *
	 * <h3>Variables</h3>
	 * - <code>:dest_max</code> int, required in transaction.sql
	 * - <code>:src_min</code> int, required in transaction.sql
	 * - <code>:delta</code> int, required in transaction.sql
	 * - <code>:dest</code> string, required in transaction.sql
	 * - <code>:src</code> string, required in transaction.sql
	 * - <code>:id</code> string, required in transaction.sql
	 */
	public const CAPITAL_TRANSACTION_CREATE = "capital.transaction.create";

}
