<?php

/*
 * Auto-generated by libasynql-fx
 * Created from init.sql, analytics.sql, transaction.sql, account.sql, init.sql, analytics.sql, transaction.sql, account.sql
 */

declare(strict_types=1);

namespace SOFe\Capital\Database;

use Generator;
use poggit\libasynql\DataConnector;
use SOFe\AwaitGenerator\Await;

final class RawQueries{
    public function __construct(private DataConnector $conn) {}

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:7
     * - resources/sqlite/account.sql:7
     * @param string $id
     * @param int $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountCreate(string $id, int $value, ) : Generator {
        $this->conn->executeInsert("capital.account.create", ["id" => $id, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:15
     * - resources/sqlite/account.sql:22
     * @param string $id
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function accountFetch(string $id, ) : Generator {
        $this->conn->executeSelect("capital.account.fetch", ["id" => $id, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:19
     * - resources/sqlite/account.sql:26
     * @param string[] $ids
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function accountFetchList(array $ids, ) : Generator {
        $this->conn->executeSelect("capital.account.fetch_list", ["ids" => $ids, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:26
     * - resources/sqlite/account.sql:33
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountLabelAdd(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeInsert("capital.account.label.add", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:39
     * - resources/sqlite/account.sql:45
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountLabelAddOrUpdate(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeInsert("capital.account.label.add_or_update", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:44
     * - resources/sqlite/account.sql:50
     * @param string $id
     * @param string $name
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function accountLabelFetch(string $id, string $name, ) : Generator {
        $this->conn->executeSelect("capital.account.label.fetch", ["id" => $id, "name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:48
     * - resources/sqlite/account.sql:54
     * @param string $id
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function accountLabelFetchAll(string $id, ) : Generator {
        $this->conn->executeSelect("capital.account.label.fetch_all", ["id" => $id, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:52
     * - resources/sqlite/account.sql:58
     * @param string[] $ids
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function accountLabelFetchAllMulti(array $ids, ) : Generator {
        $this->conn->executeSelect("capital.account.label.fetch_all_multi", ["ids" => $ids, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:32
     * - resources/sqlite/account.sql:39
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountLabelUpdate(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeChange("capital.account.label.update", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/sqlite/account.sql:17
     * @param string $id
     * @param int $delta
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountSqliteUnsafeDelta(string $id, int $delta, ) : Generator {
        $this->conn->executeChange("capital.account.sqlite.unsafe.delta", ["id" => $id, "delta" => $delta, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/account.sql:11
     * - resources/sqlite/account.sql:11
     * @param string $id
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function accountTouch(string $id, ) : Generator {
        $this->conn->executeChange("capital.account.touch", ["id" => $id, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/analytics.sql:32
     * - resources/sqlite/analytics.sql:24
     * @param string $queryHash
     * @param string $runId
     * @param int $expiry
     * @param int $limit
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function analyticsCollectUpdates(string $queryHash, string $runId, int $expiry, int $limit, ) : Generator {
        $this->conn->executeChange("capital.analytics.collect-updates", ["queryHash" => $queryHash, "runId" => $runId, "expiry" => $expiry, "limit" => $limit, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/analytics.sql:17
     * - resources/sqlite/analytics.sql:7
     * @param string $queryHash
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function analyticsCount(string $queryHash, ) : Generator {
        $this->conn->executeSelect("capital.analytics.count", ["queryHash" => $queryHash, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/analytics.sql:12
     * @param string $queryHash
     * @param int $limit
     * @param int $offset
     * @param int $orderSign
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function analyticsFetchTop(string $queryHash, int $limit, int $offset, int $orderSign, ) : Generator {
        $this->conn->executeSelect("capital.analytics.fetch-top", ["queryHash" => $queryHash, "limit" => $limit, "offset" => $offset, "orderSign" => $orderSign, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/init.sql:92
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function initMysqlProceduresTranCreate() : Generator {
        $this->conn->executeChange("capital.init.mysql.procedures.tran_create", [], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/init.sql:129
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function initMysqlProceduresTranCreate2() : Generator {
        $this->conn->executeChange("capital.init.mysql.procedures.tran_create_2", [], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/init.sql:57
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function initMysqlTables() : Generator {
        $this->conn->executeChange("capital.init.mysql.tables", [], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/sqlite/init.sql:62
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function initSqlite() : Generator {
        $this->conn->executeChange("capital.init.sqlite", [], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:17
     * @param string $id
     * @param string $src
     * @param string $dest
     * @param int $delta
     * @param int $src_min
     * @param int $dest_max
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function transactionCreate(string $id, string $src, string $dest, int $delta, int $src_min, int $dest_max, ) : Generator {
        $this->conn->executeSelect("capital.transaction.create", ["id" => $id, "src" => $src, "dest" => $dest, "delta" => $delta, "src_min" => $src_min, "dest_max" => $dest_max, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:38
     * @param string $id1
     * @param string $src1
     * @param string $dest1
     * @param int $delta1
     * @param int $src_min1
     * @param int $dest_max1
     * @param string $id2
     * @param string $src2
     * @param string $dest2
     * @param int $delta2
     * @param int $src_min2
     * @param int $dest_max2
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function transactionCreate2(string $id1, string $src1, string $dest1, int $delta1, int $src_min1, int $dest_max1, string $id2, string $src2, string $dest2, int $delta2, int $src_min2, int $dest_max2, ) : Generator {
        $this->conn->executeSelect("capital.transaction.create2", ["id1" => $id1, "src1" => $src1, "dest1" => $dest1, "delta1" => $delta1, "src_min1" => $src_min1, "dest_max1" => $dest_max1, "id2" => $id2, "src2" => $src2, "dest2" => $dest2, "delta2" => $delta2, "src_min2" => $src_min2, "dest_max2" => $dest_max2, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/sqlite/transaction.sql:9
     * @param string $id
     * @param string $src
     * @param string $dest
     * @param int $delta
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function transactionInsert(string $id, string $src, string $dest, int $delta, ) : Generator {
        $this->conn->executeInsert("capital.transaction.insert", ["id" => $id, "src" => $src, "dest" => $dest, "delta" => $delta, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:45
     * - resources/sqlite/transaction.sql:16
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function transactionLabelAdd(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeInsert("capital.transaction.label.add", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:58
     * - resources/sqlite/transaction.sql:28
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function transactionLabelAddOrUpdate(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeInsert("capital.transaction.label.add_or_update", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:63
     * - resources/sqlite/transaction.sql:33
     * @param string $id
     * @param string $name
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function transactionLabelFetch(string $id, string $name, ) : Generator {
        $this->conn->executeSelect("capital.transaction.label.fetch", ["id" => $id, "name" => $name, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:67
     * - resources/sqlite/transaction.sql:37
     * @param string $id
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function transactionLabelFetchAll(string $id, ) : Generator {
        $this->conn->executeSelect("capital.transaction.label.fetch_all", ["id" => $id, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:71
     * - resources/sqlite/transaction.sql:41
     * @param string[] $ids
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, list<array<string, mixed>>>
     */
    public function transactionLabelFetchAllMulti(array $ids, ) : Generator {
        $this->conn->executeSelect("capital.transaction.label.fetch_all_multi", ["ids" => $ids, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }

    /**
     * <h4>Declared in:</h4>
     * - resources/mysql/transaction.sql:51
     * - resources/sqlite/transaction.sql:22
     * @param string $id
     * @param string $name
     * @param string $value
     * @return Generator<mixed, 'all'|'once'|'race'|'reject'|'resolve'|array{'resolve'}|Generator<mixed, mixed, mixed, mixed>|null, mixed, int>
     */
    public function transactionLabelUpdate(string $id, string $name, string $value, ) : Generator {
        $this->conn->executeChange("capital.transaction.label.update", ["id" => $id, "name" => $name, "value" => $value, ], yield Await::RESOLVE, yield Await::REJECT);
        return yield Await::ONCE;
    }
}
